branch-defaults:
  default:
    environment: my-django-env
global:
  application_name: e-market
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: null
  workspace_type: Application
